import { ADAV } from "./ADAV.js";
import { ADBS } from "./ADBS.js";
import { ADTE } from "./ADTE.js";
import { ADUI } from "./ADUI.js";
import { ASNE } from "./ASNE.js";
import { CLCO } from "./CLCO.js";
import { DBAV } from "./DBAV.js";
import { DBBS } from "./DBBS.js";
import { GAME } from "./GAME.js";
import { HTCS } from "./HTCS.js";
import { INMA } from "./INMA.js";
import { JAAV } from "./JAAV.js";
import { JABS } from "./JABS.js";
import { JSPR } from "./JSPR.js";
import { LAYO } from "./LAYO.js";
import { MOWE } from "./MOWE.js";
import { PHPP } from "./PHPP.js";
import { PMAG } from "./PMAG.js";
import { Template } from "./Template.js";
import { VBPR } from "./VBPR.js";
import { WEBU } from "./WEBU.js";
export const listQuestion = [
  { id: "ADAV", course: ADAV },
  { id: "ADBS", course: ADBS },
  { id: "ADTE", course: ADTE },
  { id: "ADUI", course: ADUI },
  { id: "ASNE", course: ASNE },
  { id: "CLCO", course: CLCO },
  { id: "DBAV", course: DBAV },
  { id: "DBBS", course: DBBS },
  { id: "GAME", course: GAME },
  { id: "INMA", course: INMA },
  { id: "JAAV", course: JAAV },
  { id: "JABS", course: JABS },
  { id: "HTCS", course: HTCS },
  { id: "JSPR", course: JSPR },
  { id: "LAYO", course: LAYO },
  { id: "MOWE", course: MOWE },
  { id: "PHPP", course: PHPP },
  { id: "PMAG", course: PMAG },
  { id: "Template", course: Template },
  { id: "VBPR", course: VBPR },
  { id: "WEBU", course: WEBU },
];
